# Introduction

The aim of this workshop is to help you get started with using the prioritizr R package for systematic conservation planning. It is not designed to give you a comprehensive overview and you will not become an expert after completing this workshop. Instead, we want to help you understand the core principles of conservation planning and guide you through some of the common tasks involved with generating prioritizations. Phrased provocatively, we want to give you the knowledge base and confidence needed to start applying systematic conservation planning to your own work.

One of the best ways, perhaps, to learn something new is to just give it a go. As such, this workshop involves generating prioritizations for protected area establishment and performing analyses to understand them. This manual is divided into two main sections, the **Help** section provides explanations and example R code for performing common prioritization tasks (e.g. importing data, creating target data, solving conservation problems, calculating shortfalls) and the **Exercise** section contains a systematic conservation planning case-study. During this workshop, your aim is to work through the case-study in the **Exercise** section and complete the tasks and answer the questions. Since the **Exercise** section does not contain any R code, you will need to read the **Help** section for information on performing the tasks. This means that all of the code needed to complete the **Exercise** section are in the **Help** section---you just need to find them!

Finally, you are not alone in this workshop. If you are having trouble, please put your hand up and one of the instructors will help you as soon as they can. You can also ask the people sitting next to you for help too. Please note that the first thing an instructor will ask you will (probably) be "what have you tried so far?". This means that we can't help you if you haven't tried anything.
